- hosts: localhost
  tasks:
    - name: "Delete an artifactory user"
      artifactory_user:
        artifactory: "{{ lookup('env','ARTI_HOST') }}"
        admin_user: "{{ lookup('env','ARTI_USER') }}"
        admin_user_password: "{{ lookup('env','ARTI_PASS') }}"
        name: "will"
        state: 'absent'
      register: result

    - debug: msg=result