- hosts: localhost
  tasks:

    - name: Create a github Repo
      github_repo:
        github_auth_key: "..."
        name: "Hello-World"
        description: "This is your first repository"
        private: no
        has_issues: no
        has_wiki: no
        has_downloads: no
        github_account: William1444
        state: present
      register: result

    - debug: var=result
