- hosts: localhost
  tasks:
    - name: "Create/update an artifactory user"
      artifactory_user:
        artifactory: "https://artifactory.is-in-the.cloud/artifactory"
        admin_user: "admin"
        admin_user_password: "password"
        name: "will"
        state: 'absent'
      register: result

    - debug: msg=result