- hosts: localhost
  tasks:

    - name: Create an artifactory repo
      artifactory_repo:
        artifactory: "{{ lookup('env','ARTI_HOST') }}"
        user: "{{ lookup('env','ARTI_USER') }}"
        password: "{{ lookup('env','ARTI_PASS') }}"
        key: "docker-local1"
        packageType: "docker"
        description: "A docker repo"
      register: result

    - debug: var=result
