- hosts: localhost
  tasks:

    - name: Delete an artifactory repo
      artifactory_repo:
        artifactory: "https://artifactory.is-in-the.cloud/artifactory/"
        user: "{{ lookup('env','ARTI_USER') }}"
        password: "{{ lookup('env','ARTI_PASS') }}"
        key: "docker-local1"
        state: absent
        packageType: "docker"
      register: result

    - debug: var=result
